//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization
{
#if __ANDROID__
    using NoesisApp;

    [Android.App.Activity(Label = "Samples.Localization", MainLauncher = true, ConfigurationChanges =
        Android.Content.PM.ConfigChanges.ScreenSize |
        Android.Content.PM.ConfigChanges.Orientation |
        Android.Content.PM.ConfigChanges.KeyboardHidden)]
    public class MainActivity : AndroidActivity
    {
        protected override void Main()
        {
            App app = new App();
            app.Uri = "App.xaml";
            app.Run();
        }
    }
#elif __IOS__
    // TODO

#elif __UWP__
    // TODO

#else // Windows
    using System;
    using NoesisApp;

    partial class App : Application
    {
        [STAThread]
        static void Main()
        {
            App app = new App();
            app.Uri = "App.xaml";
            app.Run();
        }
    }
#endif
}
